version: '3'
services:
  app:
    build:
      context: .
    command: /bin/bash
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/effective_testing_with_rspec3_in_docker
    tty: true